// react/src/containers/App.js
import React, {Component} from 'react';
import './App.css';
import {connect} from "react-redux";
import {RootActions} from "../actions";
import {bindActionCreators} from "redux";
import {Board} from "./Board";
import {AppBar, LinearProgress, RaisedButton, Snackbar, TextField} from "material-ui";
import {Logged} from "../components/Logged";
import {Aside} from "../components/Aside";

const io = require('socket.io-client')('localhost:7777');

class App extends Component {
    componentDidMount(){
        this.initIO();
    }

    initIO(){
        io.on('errorsMessages', (msg) =>{
            this.props.actions.pushNotification(msg);
        });

        io.on('action', (...msg) =>{
            let [action, payload] = msg;
            this.props.actions[action](payload);
        })
    }

    signIn(username){
        io.send('signIn', { username:username });
    }

    createGame(){
        let username = this.refs.myInput.input.value;
        this.signIn(username);
    }

    signOut(){
        this.props.actions.signOut();
        io.disconnect();
        this.props.actions.updateGamelist([]);
        io.connect();
    }

    joinGame(gameId){
        if(this.props.player.logged) {
            io.send('joinGame', { gameId:gameId, opponent:this.props.player.username })
        } else {
            this.props.actions.pushNotification('You must login first!')
        }

    }

    resetNotification(){
        this.props.actions.resetNotification();
    }

    handleClick(y, x, id){
        if(this.props.game.gameStarted && this.props.player.nextMove && id === 'opponent') {
            io.send('shoot', { x, y, gameRoom:this.props.player.gameRoom, opponent:this.props.player.opponent });
            this.props.actions.setMove(false);
        }
    }

    startNewGame(){
        io.send('startNewGame', { opponent:this.props.player.opponent.id });
    }

    render(){
        return (
            <div className="App">
                <Aside gamelist={this.props.game.gamelist} username={this.props.player.username}
                       onClick={(id) =>{this.joinGame(id)}}/>
                <section style={{ marginLeft:'256px' }}>
                    <AppBar title={'Battleship'}
                            iconElementLeft={<div></div>}
                            iconElementRight={this.props.player.logged ?
                                <Logged onClick={() => this.signOut()} profile={this.props.player}/> : <div></div>}/>
                    <section style={{ padding:'30px' }}>
                        {this.props.game.canCreateNewGame &&
                        <RaisedButton secondary={true} label="Start new game" fullWidth={true}
                                      onClick={this.startNewGame.bind(this)}/>
                        }
                        {this.props.player.logged && !this.props.game.gameStarted &&
                        <section>
                            <h4>Waiting for new opponent!</h4>
                            <LinearProgress mode="indeterminate"/>
                        </section>
                        }
                    </section>
                    {!this.props.player.logged &&
                    <div>
                        <TextField ref={'myInput'} floatingLabelText="Username"/>&nbsp;
                        <RaisedButton label="Create game!" onClick={this.createGame.bind(this)} primary={true}/>

                    </div>
                    }
                    <h2> {this.props.errors}</h2>
                    {this.props.boards.player.length > 0 &&
                    <div className={'thegame'}>
                        <Board nextMove={!this.props.player.nextMove} name={"My Board"} board={this.props.boards.player}
                               onClick={(row, col) => this.handleClick(row, col, 'player')}/>
                        <Board nextMove={this.props.player.nextMove} name={this.props.player.opponent.name}
                               board={this.props.boards.opponent}
                               onClick={(row, col) => this.handleClick(row, col, 'opponent')}/>
                    </div>
                    }
                    <Snackbar
                        open={this.props.notification.open}
                        message={this.props.notification.message}
                        autoHideDuration={4000}
                        onRequestClose={() => this.resetNotification()}
                    />
                </section>
            </div>
        );
    }
}


const mapStateToProps = state => ({
    player      :state.player,
    errors      :state.errors,
    boards      :state.boards,
    game        :state.game,
    notification:state.game.notification
});
const mapDispatchToProps = dispatch => ({
    actions:bindActionCreators(RootActions, dispatch)
});
export default connect(
    mapStateToProps,
    mapDispatchToProps
)(App)

// angular/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { IOService } from './shared/services/io/io.service';
import { Store } from '@ngrx/store';
import { GameActions } from './core/actions/game';
import { MatSnackBar } from '@angular/material';
//import { IOService } from './shared/services/io/io.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent implements OnInit{
  usernameInput = '';
  player;
  game;
  boards;
  gamelist = [];
  constructor(
    private SocketClient:IOService,
    private store: Store<any> ,
    private actions:GameActions,
    public snackBar: MatSnackBar
  ) {
  }
  ngOnInit(): void {
    this.store.select('player').subscribe(player=>{
      this.player = player;
    });

    this.store.select('game').subscribe((game)=>{
      this.game = game;
      if(this.game.notification.open){
        this.showNotification(this.game.notification.message)
      }
    });
    this.store.select('boards').subscribe((board)=>{
      this.boards = board;
    })

  }
  showNotification(msg){
    this.snackBar.open(msg, 'Ok!', {duration: 2000}).afterDismissed().subscribe(()=>{
      this.actions.resetNotification()
      console.log('Dismissed')
    });
  }
  createGame(){
    let username = this.usernameInput;
    if(username){
      this.signIn(username);
    }
  }

  /*setGamelist(game){
    this.gamelist = game.gamelist.slice().filter(g => g.name !== this.player.username)
    console.log('Gamelist settings',this.gamelist)
  }*/
  signIn(username){
    this.SocketClient.init();
    this.SocketClient.io.send('signIn', { username:username });
  }
  signOut(){
    this.actions.signOut();
    this.SocketClient.disconnect();
    this.actions.updateGamelist([]);
  }
  joinGame(gameId, status){
    if(status === 'free'){
      if(this.player.logged){
        this.SocketClient.io.send('joinGame', { gameId:gameId, opponent:this.player.username})
      } else {
        this.actions.pushNotification('You must login first!')
      }
    } else {
      this.actions.pushNotification("Yo can't join this game! This game is busy.")
    }

  }
  cellAction(ev:any, id){
    if(this.player.nextMove && id === 'opponent'){
      this.SocketClient.io.send('shoot', { x: ev.x, y:ev.y, gameRoom:this.player.gameRoom, opponent: this.player.opponent});
      this.actions.setMove({status: false});
    }

  }
  startNewGame(){
    this.SocketClient.io.send('startNewGame', { opponent:this.player.opponent.id });
  }


}

<section fxFill>
  <mat-sidenav-container class="example-container" fxFill>
    <mat-sidenav mode="side" opened fxFlex="256px" class="mat-elevation-z2">
      <mat-toolbar color="primary">
        <h1 class="sidebar-header" [style.fontSize]="'20px'">Game Rooms</h1>
      </mat-toolbar>
      <mat-nav-list *ngIf="game">
        <mat-list-item *ngFor="let item of game.gamelist" (click)="joinGame(item.gameId, item.status)">
          <a matLine disabled="true"> {{item.name}} </a>
          <button mat-icon-button><mat-icon [ngClass]="{'icon-green':item.status === 'free','icon-red'  :item.status === 'game'}">games</mat-icon></button>
          <!--<mat-icon matListIcon>game</mat-icon>-->
        </mat-list-item>
      </mat-nav-list>
    </mat-sidenav>
    <mat-sidenav-content>
      <mat-toolbar color="primary">
        <h1 class="sidebar-header" [style.fontWeight]="400">Battleship</h1>
        <span id="user-section" fxLayout="row" *ngIf="player.logged">
           <picture>
                <img [src]="player.avatar" alt=""/>
          </picture>
          <span>{{player.username}}</span>
        </span>
        <button mat-icon-button [matMenuTriggerFor]="menu" *ngIf="player && player.logged"><mat-icon>more_vert</mat-icon></button>
        <mat-menu #menu="matMenu">
          <button mat-menu-item (click)="signOut()">Sign Out</button>
        </mat-menu>
      </mat-toolbar>
      <section [style.padding]="'30px'" fxLayout="column wrap" fxLayoutAlign="center center" >
        <div *ngIf="!player.logged">
          <mat-form-field>
            <input matInput [(ngModel)]="usernameInput" placeholder="Username"/>
          </mat-form-field>
          <button mat-raised-button (click)="createGame()" color="primary">Create game!</button>
        </div>
        <section fxFlex="5">
          <button mat-raised-button color="accent" (click)="startNewGame()" *ngIf="game.canCreateNewGame">Start new game</button>
          <section *ngIf="player.logged && !game.gameStarted ">
            <h4>Waiting for new opponent!</h4>
            <mat-progress-bar mode="indeterminate"></mat-progress-bar>
          </section>
        </section>
        <div fxLayout="row" class="thegame" *ngIf="player.joined">
          <bs-board *ngIf="boards.player" [boardName]="'My Board'"
                    [board]="boards.player" [move]="!player.nextMove"
                    (cellAction)="cellAction($event, 'player')"> </bs-board>
          <bs-board *ngIf="boards.opponent" [boardName]="player.opponent.name"
                    [board]="boards.opponent" [move]="player.nextMove"
                    (cellAction)="cellAction($event, 'opponent')"> </bs-board>
        </div>
      </section>
    </mat-sidenav-content>
  </mat-sidenav-container>
</section>
